---
- hosts: all
  tasks:
    - name: Example clone of a single branch
      ansible.builtin.git:
        repo: https://github.com/0zob/generate-files.git
        dest: "{{ dest_dir }}"
        single_branch: yes
        version: master
        force: yes

    - name: "Install app dependences"
      shell: "cd {{ dest_dir }} && npm install"

    - name: "Create service for app"
      template:
        src: templates/pandora-files.service.j2
        dest: /etc/systemd/system/pandora-files.service
      become: yes

    - name: "Restart app service"
      service:
        name: pandora-files
        state: restarted
      become: yes
